# permissions for end users to view cachedimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cachedimage-viewer-role
rules:
- apiGroups:
  - kuik.enix.io
  resources:
  - cachedimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - cachedimages/status
  verbs:
  - get
