apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kuik-serving-cert
  name: kuik-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: kuik-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-v1-pod
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  objectSelector:
    matchExpressions:
    - key: kube-image-keeper.enix.io/image-caching-policy
      operator: NotIn
      values:
      - ignore
    {{- range .Values.controllers.webhook.objectSelector.matchExpressions }}
    - {{ . | toYaml | indent 6 | trim  }}
    {{- end }}
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
